### ISSUE TITLE
[HyperNova] Fix number of public inputs/outptus even requirement

### ISSUE THREAD

**Issue by oskarth** [privacy-scaling-explorations/Nova#30]
# Problem

Currently in `hypernova` branch we've commented out requirement in `src/r1cs.rs` that public inputs/outputs are even. If this is uncommented the tests don't pass.

## Details

```
diff --git a/src/r1cs.rs b/src/r1cs.rs
index 36133f5..03e50af 100644
--- a/src/r1cs.rs
+++ b/src/r1cs.rs
@@ -119,9 +119,9 @@ impl<G: Group> R1CSShape<G> {
     }
 
     // // We require the number of public inputs/outputs to be even
-    // if num_io % 2 != 0 {
-    //   return Err(NovaError::OddInputLength);
-    // }
+    if num_io % 2 != 0 {
+      return Err(NovaError::OddInputLength);
+    }
 ```
 
 Results in:
 
 ```
 [...]
---- ccs::cccs::tests::test_compute_Q stdout ----
thread 'ccs::cccs::tests::test_compute_Q' panicked at 'called `Result::unwrap()` on an `Err` value: OddInputLength', src/ccs/mod.rs:323:71

---- ccs::util::tests::test_compute_all_sum_Mz_evals stdout ----
thread 'ccs::util::tests::test_compute_all_sum_Mz_evals' panicked at 'called `Result::unwrap()` on an `Err` value: OddInputLength', src/ccs/mod.rs:323:71

---- ccs::util::tests::test_compute_sum_Mz_over_boolean_hypercube stdout ----
thread 'ccs::util::tests::test_compute_sum_Mz_over_boolean_hypercube' panicked at 'called `Result::unwrap()` on an `Err` value: OddInputLength', src/ccs/mod.rs:323:71


failures:
    ccs::cccs::tests::test_Q_against_q
    ccs::cccs::tests::test_compute_Q
    ccs::cccs::tests::test_compute_q
    ccs::lcccs::tests::satisfied_ccs_is_satisfied_lcccs
    ccs::lcccs::tests::test_bad_v_j
    ccs::lcccs::tests::test_lcccs_v_j
    ccs::multifolding::tests::test_compute_g
    ccs::multifolding::tests::test_compute_sigmas_and_thetas
    ccs::multifolding::tests::test_lcccs_fold
    ccs::util::tests::test_compute_all_sum_Mz_evals
    ccs::util::tests::test_compute_sum_Mz_over_boolean_hypercube
    ```
    
  ## Acceptance criteria
    
  Re-enable this requirement by default to make experimental code mergeable.
   
  1) Either with feature flag (quick, easy, hacky)
  2) Fix inputs to be even

**Comment by oskarth** [comment]
Did 1 here https://github.com/privacy-scaling-explorations/Nova/pull/15/commits/20ba46c808f1cc4e19e6e324318d8348ea5f05b0

2 needs to adjust `gen_test_ccs` fn
